version: '3.9'

services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: PostgresDB
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - tg_net

  minio:
    image: minio/minio:latest
    container_name: tgshop_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    volumes:
      - minio_data:/data
    networks:
      - tg_net

volumes:
  postgres_data:
  minio_data:

networks:
  tg_net:
    driver: bridge