# Generated by Django 5.2.3 on 2025-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productquestion_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquestion',
            name='text',
            field=models.TextField(default='No text provided'),
            preserve_default=False,
        ),
    ]
