# Generated by Django 5.2.3 on 2025-06-15 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productquestion_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquestion',
            name='source',
        ),
        migrations.RemoveField(
            model_name='productquestion',
            name='text',
        ),
        migrations.CreateModel(
            name='ProductQuestionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.productquestion')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
