# Generated by Django 5.2.3 on 2025-06-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_productquestion_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquestion',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marketplace'),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='text',
            field=models.TextField(default='No data'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductQuestionMessage',
        ),
    ]
