# Generated by Django 5.2.3 on 2025-06-15 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productquestion_marketplace_productquestion_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='source',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marketplace'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('owner', 'Владелец'), ('ai', 'ИИ')], default='No data', max_length=16),
            preserve_default=False,
        ),
    ]
