# Generated by Django 5.2.3 on 2025-06-15 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_questionanswer_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProductQuestionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('manager', 'Менеджер'), ('owner', 'Владелец'), ('ai', 'ИИ')], max_length=16)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marketplace')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.productquestionmessage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.productquestion')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
